### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by greatersleep** [styxsys0927/LightK-DSGCN#1]
Where are the sample.csv and adjacency matrix files

**Comment by styxsys0927** [comment]
Please check [this directory](https://www.dropbox.com/scl/fo/hntadnj0u5fizqlq4uwbb/ALLVjF0LeGTbWYJunSAG9z4?rlkey=olh8b4b0tvbiunrujus77lf4j&st=ha0zhrk0&dl=0).
